# Generated by Django 4.0.5 on 2022-10-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_sepet_fiyat_alter_sepet_adet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stok',
            field=models.IntegerField(default=50, verbose_name='Stok'),
            preserve_default=False,
        ),
    ]
